# Generated by Django 5.2 on 2025-05-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('usage', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('refills', models.IntegerField()),
            ],
        ),
    ]
