# Generated by Django 5.2 on 2025-05-01 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('M', 'Morning'), ('N', 'Noon'), ('E', 'Evening'), ('B', 'Bedtime')], default='M', max_length=1)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.medication')),
            ],
        ),
    ]
