# Generated by Django 5.2 on 2025-05-02 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_feeding_delete_dosing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='dosage',
            new_name='dosage_info',
        ),
        migrations.CreateModel(
            name='Dosage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Dosage Date')),
                ('dose', models.CharField(choices=[('M', 'Morning'), ('N', 'Noon'), ('E', 'Evening'), ('B', 'Bedtime')], default='M', max_length=1)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.medication')),
            ],
        ),
        migrations.DeleteModel(
            name='Feeding',
        ),
    ]
